name: mmoInfoCoords
main: mmo.Info.MMOInfoCoords
version: 0.1
website: http://forums.bukkit.org/threads/
author: Rycochet <rycochet@rycochet.com>
depend: [mmoCore,mmoInfo]

description: Adds {coords} to the info tokens
permissions:
  info.coords:
    description: Shows the current player coordinates
    default: op
