name: mmoInfoCoords
version: ${releaseVersion}.${buildNumber}
description: Adds a {coords} token to the mmoInfo token list.
author: mmoMinecraftDev
website: http://mmo.me.uk

main: mmo.Info.MMOInfoCoords
depend: [Spout, mmoCore, mmoInfo]


permissions:
    mmo.info.coords:
        description: Allows {coords} to show the current player coordinates
        default: op
